apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: accounts-provider 
spec: 
  selector: 
    matchLabels: 
      app: accounts-provider 
  template: 
    metadata: 
      labels: 
        app: accounts-provider 
    spec: 
      containers: 
      - name: accounts-provider 
        image: yuragranovsky/accounts-provider 
        resources: 
          limits: 
            memory: "300Mi" 
            cpu: "300m" 
        env: 
        - name: CONFIG_SERVER_HOST 
          valueFrom:  
            configMapKeyRef: 
              name: pm-config-map 
              key: configServer 
        - name: MONGO_PASSWORD 
          valueFrom: 
            secretKeyRef: 
              key: mongoPassword 
              name: pm-secret  
        ports:
        - containerPort: 8787      
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-provider
spec:
  selector:
    app: accounts-provider
  ports:
  - port: 8787
    targetPort: 8787
              